version: "3.8"

services:
    postgres:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: dockeruser
            POSTGRES_PASSWORD: dockerpassword
            POSTGRES_DB: dockerdb
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data

    backend:
        container_name: weatherforecastbackend
        build: ./backend
        ports:
            - "8080:8080"
        depends_on:
            - postgres
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dockerdb
            SPRING_DATASOURCE_USERNAME: dockeruser
            SPRING_DATASOURCE_PASSWORD: dockerpassword

    frontend:
        container_name: weatherforecastfrontend
        build: ./frontend
        ports:
            - "3000:3000"
        depends_on:
            - backend

volumes:
    postgres-data:
